apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: autoload
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: autoload
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 90